Numpy Practice

In [1]:
import numpy as np
print(np.__version__)

1.21.5


In [2]:
arr=np.array(10)
arr

array(10)

In [4]:
arr= np.array([10,11])
arr

array([10, 11])

In [7]:
arr= np.array([[10,11],[12,13]])
print(arr)

[[10 11]
 [12 13]]


Array in numpy with all dimensions

In [8]:
print(np.array(10) )# 0D

print(np.array([1,2])) # 1D

print(np.array([[1,2],[3,4]])) # 2D

print(np.array([  [  [1,2],[3,4]  ]  ,  [   [5,6],[7,8]  ]  ])) # 3D

10
[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ndmin=5

In [9]:
arr = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[6,7,8,9,10]]])
print(arr)
# print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 6  7  8  9 10]]]
(3, 1, 5)


filling arrays with auto elements

In [10]:
import numpy as np

arr = np.zeros((3,1,5))
print(arr)

[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


In [11]:
arr=np.ones((4,8,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
arr= np.arange(10,21,3)
print(arr)

[10 13 16 19]


Sorting Arrays

In [13]:
arr= np.array([2,1,5,6,3,8,7,4])

sorted_array= np.sort(arr)
print(sorted_array)

[1 2 3 4 5 6 7 8]


Sort alphabets or names

In [14]:
arr= np.array(["Apple","Zebra","Tea"])

sorted_array= np.sort(arr)
print(sorted_array)

['Apple' 'Tea' 'Zebra']


Sorting 2d array

In [15]:
arr=np.array([[6,2,3],[9,5,6]])
print( np.sort(arr)  )

[[2 3 6]
 [5 6 9]]


In [16]:
arr= np.array([50,20,300,40,-5,65,70,85])

print(arr[0:2])

[50 20]


In [17]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,2])

[[10 20 21 22 25]
 [30 40 41 42 43]]
41


In [18]:
mat=np.array([  [[21,22,25],[41,42,43]]  , [[50,51,52],[60,61,62]]  ])
print(mat)
print("Value:",mat[1,1,2])

[[[21 22 25]
  [41 42 43]]

 [[50 51 52]
  [60 61 62]]]
Value: 62


In [19]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:5:1])

[2 3 4 5]


In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,1:4])


[6 7 8]


In [21]:
arr=np.array([2,50,40,60,70,40])

val=np.where(arr==40)

print(val)

(array([2, 5], dtype=int64),)


In [22]:
arr=np.array([10,20,50,60])

val=np.searchsorted(arr,[-10,40,55])
val

array([0, 2, 3], dtype=int64)

reshape array

In [23]:
arr=np.array([[1,2,],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

numpy filter

In [4]:
import numpy as np
arr = np.array([10,30,20,60,70])
b=[True,False,False,False,True]
newarr =arr[b]
print(newarr)


[10 70]


In [8]:
seq =[0,1,2,3,4,5,6,7,8,9,10,11,12]
result = filter(lambda x : x % 2 !=0,seq)
print(list(result))

[1, 3, 5, 7, 9, 11]


In [16]:
seq =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
result = filter(lambda x : x % 2 ==0,seq)
print(list(result))

[2, 4, 6, 8, 10, 12]


concatenate()

In [28]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.arange(12,18).reshape(2,3)
# print(c)
result=np.concatenate((a,b,c))
print(result)


[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]
 [15 16 17]]


In [29]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
result=np.concatenate((a,b))
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [34]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  5,  6,  7],
       [ 3,  4,  5,  8,  9, 10]])

stack()

In [5]:
import numpy as np
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.stack((a,b),axis=-1)
print(c)

[[[ 0  5]
  [ 1  6]
  [ 2  7]]

 [[ 3  8]
  [ 4  9]
  [ 5 10]]]


vstack()

In [3]:
import numpy as np
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

hstack()

In [1]:
import numpy as np
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(6,12).reshape(2,3)
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [2]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.arange(12,18).reshape(2,3)
# print(c)
result=np.vstack((a,b,c))
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]
 [15 16 17]]


In [3]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.arange(12,18).reshape(2,3)
# print(c)
result=np.hstack((a,b,c))
print(result)

[[ 0  1  2  5  6  7 12 13 14]
 [ 3  4  5  8  9 10 15 16 17]]


dstack()

In [4]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.arange(12,18).reshape(2,3)
# print(c)
result=np.dstack((a,b,c))
print(result)

[[[ 0  5 12]
  [ 1  6 13]
  [ 2  7 14]]

 [[ 3  8 15]
  [ 4  9 16]
  [ 5 10 17]]]


PANDAS

In [1]:
import pandas as pd


series()

In [18]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6])
S=pd.Series((a))
S



0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [21]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6])
S=pd.Series(a, index=['a','b','c','d','e','f'])

S['a']



a    1
b    2
c    3
d    4
e    5
f    6
dtype: int32

In [22]:
l1=[1,2,3,4]
pd.Series(l1)


0    1
1    2
2    3
3    4
dtype: int64

homework

In [25]:
import pandas as pd

student_data = {
    'Name': ['John', 'Emma', 'Adam'],
    'Age': [20, 19, 21],
    'Grade': [8, 9, 7]
}
df = pd.DataFrame(student_data)
print(df)

   Name  Age  Grade
0  John   20      8
1  Emma   19      9
2  Adam   21      7


In [26]:
import pandas as pd

# Create a dictionary with student information
student_data = {
    'Name': ['John', 'Emma', 'Adam', 'John', 'Adam'],
    'Age': [20, 19, 21, 20, 21],
    'Grade': [8, 9, 7, 8, 7]
}

# Convert the dictionary to a DataFrame
df = pd.DataFrame(student_data)

# Drop duplicate rows based on all columns
unique_students = df.drop_duplicates()

# Print the unique student information
print(unique_students)

   Name  Age  Grade
0  John   20      8
1  Emma   19      9
2  Adam   21      7
