numpy filter

In [4]:
import numpy as np
arr = np.array([10,30,20,60,70])
b=[True,False,False,False,True]
newarr =arr[b]
print(newarr)


[10 70]


In [8]:
seq =[0,1,2,3,4,5,6,7,8,9,10,11,12]
result = filter(lambda x : x % 2 !=0,seq)
print(list(result))

[1, 3, 5, 7, 9, 11]


In [16]:
seq =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
result = filter(lambda x : x % 2 ==0,seq)
print(list(result))

[2, 4, 6, 8, 10, 12]


concatenate()

In [28]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
c=np.arange(12,18).reshape(2,3)
# print(c)
result=np.concatenate((a,b,c))
print(result)


[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]
 [15 16 17]]


In [29]:
a=np.arange(6).reshape(2,3)
# print(a)
b=np.arange(5,11).reshape(2,3)
# print(b)
result=np.concatenate((a,b))
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [34]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  5,  6,  7],
       [ 3,  4,  5,  8,  9, 10]])